# Generated by Django 3.2.8 on 2021-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211120_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='side_img1',
            field=models.ImageField(null=True, upload_to='product-img'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_img2',
            field=models.ImageField(null=True, upload_to='product-img'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_img3',
            field=models.ImageField(null=True, upload_to='product-img'),
        ),
    ]
