# Generated by Django 3.2.8 on 2021-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211120_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='side_img4',
            field=models.ImageField(null=True, upload_to='product-img'),
        ),
    ]
