# Generated by Django 3.2.8 on 2021-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_side_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_img1',
            field=models.ImageField(blank=True, null=True, upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_img2',
            field=models.ImageField(blank=True, null=True, upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_img3',
            field=models.ImageField(blank=True, null=True, upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_img4',
            field=models.ImageField(blank=True, null=True, upload_to='product-img'),
        ),
    ]
