# Generated by Django 3.2.8 on 2021-11-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211120_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Single_Product_detail',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
